// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbcOURAwrzJ7K2J2phqqEt8kVQzl7GNRw',
    appId: '1:449038684187:web:3919a750269a80593628be',
    messagingSenderId: '449038684187',
    projectId: 'tiktokclone-d5672',
    authDomain: 'tiktokclone-d5672.firebaseapp.com',
    storageBucket: 'tiktokclone-d5672.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhhdw3H-NV26FnCrvV8k_TO3psKHPFlBg',
    appId: '1:449038684187:android:05aaf5d0647ae0f83628be',
    messagingSenderId: '449038684187',
    projectId: 'tiktokclone-d5672',
    storageBucket: 'tiktokclone-d5672.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJOI0Ijx9lifVH8OmhL8ufmUroa0C-MCw',
    appId: '1:449038684187:ios:2094ece28cfabf703628be',
    messagingSenderId: '449038684187',
    projectId: 'tiktokclone-d5672',
    storageBucket: 'tiktokclone-d5672.firebasestorage.app',
    iosBundleId: 'com.example.tiktokCloneZee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJOI0Ijx9lifVH8OmhL8ufmUroa0C-MCw',
    appId: '1:449038684187:ios:2094ece28cfabf703628be',
    messagingSenderId: '449038684187',
    projectId: 'tiktokclone-d5672',
    storageBucket: 'tiktokclone-d5672.firebasestorage.app',
    iosBundleId: 'com.example.tiktokCloneZee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbcOURAwrzJ7K2J2phqqEt8kVQzl7GNRw',
    appId: '1:449038684187:web:1235e29f4ab2344c3628be',
    messagingSenderId: '449038684187',
    projectId: 'tiktokclone-d5672',
    authDomain: 'tiktokclone-d5672.firebaseapp.com',
    storageBucket: 'tiktokclone-d5672.firebasestorage.app',
  );
}
